jobs:
- job: tests_cypress
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml
  - template: composer-install-step.yml
  - template: prepare-db-step.yml
  - template: seed-test-db-step.yml

  - bash: |
      php -S localhost:8000 -t public scripts/tests/server-cc.php &
    displayName: 'Run http server'

  - bash: |
      $(yarn bin)/cypress run --config "baseUrl=http://localhost:8000" --record --reporter mocha-multi-reporters --reporter-options configFile=tests/cypress/cypressmocha.json --key ${CYPRESS_RECORD_KEY}
    displayName: 'Run cypress tests'
    env:
      CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)

  - bash: |
      vendor/bin/phpcov merge --clover=results/coverage_c.xml results/coverage/
      rm -rf results/coverage
    displayName: 'Fix coverage'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'results'
      targetPath: 'results'
